### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key: hU2n9fib361eb41c31758ee4bUlCfmGI

origin=64999&destination=64942&weight=1000&courier=jne